### ISSUE TITLE
Uploader with random unique filenames

### ISSUE THREAD

**Issue by bdsword** [kirtithorat/carrierwave-crop#13]
As  mention [here](https://github.com/carrierwaveuploader/carrierwave#recreating-versions)，when you are [generating random unique filenames](https://github.com/carrierwaveuploader/carrierwave/wiki/How-to%3A-Create-random-and-unique-filenames-for-all-versioned-files), `recreate_versions!` doesn't save the new filename to the database.

So I have to call save! by myself after update_attributes

``` ruby
def update
   @model.update(model_update_params)
   @model.save!
   respond_with @model
 end
```

Is there a better solution?

**Comment by kirtithorat** [comment]
@bdsword Shouldn't this be raised in `carrierwave` gem as it handles the uploading & saving of files part?

**Comment by bdsword** [comment]
Thank you for your prompt reply.

After some research, the extra `save!` seems a restriction, and it's the only solution for this problem.

I guess there is no way to put this extra `save!` inside [crop_image](https://github.com/kirtithorat/carrierwave-crop/blob/master/lib/carrierwave/crop/model_additions.rb#L48-L53).
`cause it's inside after_update callback.

So I'll keep using the extra `save!`.

**Comment by kirtithorat** [comment]
Close #13
